apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: nginx-demo
    repoURL: https://github.com/Iyad87/nginx-helm-chart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true